# Generated by Django 5.2.14 on 2026-05-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_factcitation_evidence_chunk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='layout',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='requirement',
            name='source_row',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
