# Generated by Django 5.2.14 on 2026-05-30 06:24

from django.db import migrations, models

LEGACY_TYPE_MAP = {
    "unbacked": "unbacked_claim",
    "gap": "implementation_gap",
    "drift": "stale_fact",
    "stale": "stale_fact",
}


def remap_legacy_types(apps, schema_editor):
    Issue = apps.get_model("core", "Issue")
    for old, new in LEGACY_TYPE_MAP.items():
        Issue.objects.filter(type=old).update(type=new)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_questionnaire_layout_requirement_source_row'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='issue',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('missing_policy', 'Missing Policy'), ('missing_evidence', 'Missing Evidence'), ('implementation_gap', 'Implementation Gap'), ('contradiction', 'Contradiction'), ('unbacked_claim', 'Unbacked Claim'), ('stale_fact', 'Stale Fact'), ('commitment', 'Commitment')], max_length=32),
        ),
        migrations.RunPython(remap_legacy_types, migrations.RunPython.noop),
    ]
