# Generated by Django 5.2.14 on 2026-05-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_answer_audited_at_answer_reused_from_answer_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='normalized_key',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
