import type { Issue, Requirement } from "@/lib/types";

export const requirements: Requirement[] = [
  {
    id: "R-001",
    bank: "Meridian Trust",
    category: "Encryption",
    question: "Is customer data encrypted at rest?",
    status: "answered",
    confidence: 0.94,
    citations: 3,
    updated: "2026-05-22",
  },
  {
    id: "R-002",
    bank: "Meridian Trust",
    category: "Certifications",
    question: "Provide your most recent SOC 2 Type II report.",
    status: "flagged",
    confidence: 0.38,
    citations: 0,
    updated: "2026-05-24",
  },
  {
    id: "R-003",
    bank: "Meridian Trust",
    category: "Access Control",
    question: "Describe your access control and least-privilege model.",
    status: "answered",
    confidence: 0.88,
    citations: 2,
    updated: "2026-05-21",
  },
  {
    id: "R-004",
    bank: "Sterling National",
    category: "Incident Response",
    question: "What is your incident response SLA for critical events?",
    status: "draft",
    confidence: 0.61,
    citations: 1,
    updated: "2026-05-25",
  },
  {
    id: "R-005",
    bank: "Sterling National",
    category: "Encryption",
    question: "Is data encrypted in transit using TLS 1.2 or higher?",
    status: "answered",
    confidence: 0.97,
    citations: 4,
    updated: "2026-05-20",
  },
  {
    id: "R-006",
    bank: "Sterling National",
    category: "Data Retention",
    question: "State your data retention and deletion policy.",
    status: "flagged",
    confidence: 0.44,
    citations: 1,
    updated: "2026-05-26",
  },
  {
    id: "R-007",
    bank: "Halcyon Bank",
    category: "Business Continuity",
    question: "Do you maintain a tested disaster recovery plan?",
    status: "answered",
    confidence: 0.82,
    citations: 2,
    updated: "2026-05-19",
  },
  {
    id: "R-008",
    bank: "Halcyon Bank",
    category: "Vendor Management",
    question: "List subprocessors with access to customer data.",
    status: "unanswered",
    confidence: 0,
    citations: 0,
    updated: "2026-05-27",
  },
  {
    id: "R-009",
    bank: "Halcyon Bank",
    category: "Access Control",
    question: "Is multi-factor authentication enforced for all staff?",
    status: "answered",
    confidence: 0.91,
    citations: 2,
    updated: "2026-05-18",
  },
  {
    id: "R-010",
    bank: "Meridian Trust",
    category: "Monitoring",
    question: "Describe your security logging and monitoring stack.",
    status: "draft",
    confidence: 0.66,
    citations: 1,
    updated: "2026-05-23",
  },
  {
    id: "R-011",
    bank: "Sterling National",
    category: "Certifications",
    question: "Are you ISO 27001 certified? Provide the certificate.",
    status: "flagged",
    confidence: 0.29,
    citations: 0,
    updated: "2026-05-28",
  },
  {
    id: "R-012",
    bank: "Halcyon Bank",
    category: "Encryption",
    question: "What key management system protects encryption keys?",
    status: "answered",
    confidence: 0.85,
    citations: 2,
    updated: "2026-05-17",
  },
];

export const issues: Issue[] = [
  {
    id: "I-101",
    type: "unbacked",
    requirementId: "R-002",
    bank: "Meridian Trust",
    description: "SOC 2 answer cites no source document.",
    status: "open",
    opened: "2026-05-24",
  },
  {
    id: "I-102",
    type: "contradiction",
    requirementId: "R-006",
    bank: "Sterling National",
    description: "Retention stated as 90 days here, 12 months in DPA fact.",
    status: "open",
    opened: "2026-05-26",
  },
  {
    id: "I-103",
    type: "gap",
    requirementId: "R-008",
    bank: "Halcyon Bank",
    description: "No subprocessor list exists in the fact base.",
    status: "open",
    opened: "2026-05-27",
  },
  {
    id: "I-104",
    type: "unbacked",
    requirementId: "R-011",
    bank: "Sterling National",
    description: "ISO 27001 claim has no certificate fact attached.",
    status: "open",
    opened: "2026-05-28",
  },
  {
    id: "I-105",
    type: "stale",
    requirementId: "R-007",
    bank: "Halcyon Bank",
    description: "DR plan fact last reviewed 14 months ago.",
    status: "open",
    opened: "2026-05-15",
  },
  {
    id: "I-106",
    type: "drift",
    requirementId: "R-004",
    bank: "Sterling National",
    description: "IR SLA fact updated; 2 prior answers not re-synced.",
    status: "open",
    opened: "2026-05-25",
  },
  {
    id: "I-107",
    type: "contradiction",
    requirementId: "R-003",
    bank: "Meridian Trust",
    description: "Least-privilege claim conflicts with admin-access fact.",
    status: "closed",
    opened: "2026-05-10",
  },
];

export const coverageByCategory = [
  { category: "Encryption", backed: 3, unbacked: 0 },
  { category: "Access Control", backed: 2, unbacked: 0 },
  { category: "Certifications", backed: 0, unbacked: 2 },
  { category: "Incident Resp.", backed: 0, unbacked: 1 },
  { category: "Data Retention", backed: 0, unbacked: 1 },
  { category: "Continuity", backed: 1, unbacked: 0 },
  { category: "Monitoring", backed: 1, unbacked: 0 },
  { category: "Vendor Mgmt", backed: 0, unbacked: 1 },
];

export const answersOverTime = [
  { week: "W17", answered: 4, flagged: 1 },
  { week: "W18", answered: 9, flagged: 2 },
  { week: "W19", answered: 14, flagged: 3 },
  { week: "W20", answered: 21, flagged: 3 },
  { week: "W21", answered: 28, flagged: 4 },
];
